language: c

matrix:
  include:
    - os: linux
      dist: bionic
      addons:
        apt:
          packages:
            - bubblewrap
    # - os: osx
    #   osx_image: xcode10.3

before_script:
  - git clone https://github.com/asdf-vm/asdf.git
  - . asdf/asdf.sh

script:
  - asdf plugin-test ocaml $TRAVIS_BUILD_DIR
